import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Spinner } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          タイトル
        </h1>

        <p className={styles.description}>
          なにがしなにがし
        </p>

        


      </main>
    </div>
  )
}
